name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo & checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x

      - name: Install npm packages
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Upload production-ready build files as artifact
        uses: actions/upload-artifact@v2
        with:
          name: production
          path: ./build

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production
          path: ./build

      - name: Deploy to Github pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
