name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo & checkout code
        uses: actions/checkout@v4.2.0

      - name: Install Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 14.x

      - name: Install npm packages
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Upload production-ready build files as artifact
        uses: actions/upload-artifact@v3.2.1-node20
        with:
          name: production
          path: ./build

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: production
          path: ./build

      - name: Deploy to Github pages
        uses: crazy-max/ghaction-github-pages@v4.0.0

        with:
          target_branch: gh-pages
          build_dir: ./build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
